//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRINTERNSHIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class All_employee
    {
        public string EMCMPY { get; set; }
        public string EMEMP { get; set; }
        public string EMNAME { get; set; }
        public string EMDEPT { get; set; }
        public string EMLOC { get; set; }
        public string EMJOBD { get; set; }
        public string EMJOBA { get; set; }
        public string EMADD1 { get; set; }
        public string EMADD2 { get; set; }
        public string EMADD3 { get; set; }
        public string EMASN { get; set; }
        public string EMBEDU { get; set; }
        public string EMBIRT { get; set; }
        public string EMBUSL { get; set; }
        public string EMBUSR { get; set; }
        public string EMBUSS { get; set; }
        public string SUPNAME { get; set; }
        public string EMPAYT { get; set; }
        public string EMRELI { get; set; }
        public string EMSEXT { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public string SECT_CODE { get; set; }
        public string SECT_NAME { get; set; }
        public string JOB_CODE { get; set; }
        public string Description { get; set; }
        public string EMITAX { get; set; }
        public string EMUSID { get; set; }
        public string EMUNIO { get; set; }
        public string EMITST { get; set; }
        public string EMWKHR { get; set; }
        public string EMHTLC { get; set; }
        public string EMGRAD { get; set; }
        public string EMMRST { get; set; }
        public string EMSUP_ { get; set; }
        public string OLDOCONT { get; set; }
        public string EMEMST { get; set; }
        public string ENDCONT { get; set; }
        public string EMCOMM { get; set; }
        public string EMTERM { get; set; }
        public string EMTREF { get; set; }
        public string EMSTAT { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string TOTALHOURS { get; set; }
        public string TOTALYEARS { get; set; }
        public string DETAILWORKEXPERIENCE { get; set; }
        public string LABEL_3 { get; set; }
        public string LABEL_2 { get; set; }
        public string LABEL_1 { get; set; }
        public string EOC { get; set; }
        public string BUS_ROUTE { get; set; }
        public string PSID { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string BPJS { get; set; }
        public string BPJS_Ketenagakerjaan { get; set; }
        public string EKTP { get; set; }
        public string EMEMAD { get; set; }
    }
}
