//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRINTERNSHIP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBModel : DbContext
    {
        public DBModel()
            : base("name=DBModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departement> Departements { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Intern_Activity> Intern_Activity { get; set; }
        public virtual DbSet<Intern_Attendance> Intern_Attendance { get; set; }
        public virtual DbSet<Intern_AttendanceApproval> Intern_AttendanceApproval { get; set; }
        public virtual DbSet<Intern_MasterData> Intern_MasterData { get; set; }
        public virtual DbSet<Intern_Periode> Intern_Periode { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<permission> permissions { get; set; }
        public virtual DbSet<Public_Holidays> Public_Holidays { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<SelfService_EmailService> SelfService_EmailService { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Temp_AttendanceIntern> Temp_AttendanceIntern { get; set; }
        public virtual DbSet<Temp_AttendanceInternIn> Temp_AttendanceInternIn { get; set; }
        public virtual DbSet<Temp_AttendanceInternOut> Temp_AttendanceInternOut { get; set; }
        public virtual DbSet<Temp_InternActivity> Temp_InternActivity { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<nbr> nbrs { get; set; }
        public virtual DbSet<Role_permissions> Role_permissions { get; set; }
        public virtual DbSet<All_employee> All_employee { get; set; }
        public virtual DbSet<ListUser> ListUsers { get; set; }
        public virtual DbSet<RoleList> RoleLists { get; set; }
        public virtual DbSet<RolePermission> RolePermissions { get; set; }
        public virtual DbSet<VwIntern_AbsLate> VwIntern_AbsLate { get; set; }
        public virtual DbSet<VwIntern_MasterDataIntern> VwIntern_MasterDataIntern { get; set; }
        public virtual DbSet<VwIntern_ReportPayment> VwIntern_ReportPayment { get; set; }
        public virtual DbSet<Intern_DetailContract> Intern_DetailContract { get; set; }
        public virtual DbSet<Historical_employee> Historical_employee { get; set; }
        public virtual DbSet<Emergency_employee> Emergency_employee { get; set; }
        public virtual DbSet<Intern_ListUsers> Intern_ListUsers { get; set; }
        public virtual DbSet<NewCalendarEvent> NewCalendarEvents { get; set; }
        public virtual DbSet<VwIntern_DashboardActLastWeek> VwIntern_DashboardActLastWeek { get; set; }
        public virtual DbSet<EmployeeDress> EmployeeDresses { get; set; }
        public virtual DbSet<GradeView> GradeViews { get; set; }
        public virtual DbSet<SALARY> SALARies { get; set; }
        public virtual DbSet<TotalHour> TotalHours { get; set; }
        public virtual DbSet<Intern_AttendanceNew> Intern_AttendanceNew { get; set; }
        public virtual DbSet<Report_UmurEmployee> Report_UmurEmployee { get; set; }
    
        public virtual ObjectResult<Intern_ListAttendance_Result> Intern_ListAttendance(string startDate, string endDate)
        {
            var startDateParameter = startDate != null ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Intern_ListAttendance_Result>("Intern_ListAttendance", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<Intern_ListAttendanceIntern_Result> Intern_ListAttendanceIntern(string startDate, string endDate, string kPK)
        {
            var startDateParameter = startDate != null ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            var kPKParameter = kPK != null ?
                new ObjectParameter("KPK", kPK) :
                new ObjectParameter("KPK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Intern_ListAttendanceIntern_Result>("Intern_ListAttendanceIntern", startDateParameter, endDateParameter, kPKParameter);
        }
    
        public virtual ObjectResult<Intern_ListAttendanceInternAll_Result> Intern_ListAttendanceInternAll(string kPK)
        {
            var kPKParameter = kPK != null ?
                new ObjectParameter("KPK", kPK) :
                new ObjectParameter("KPK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Intern_ListAttendanceInternAll_Result>("Intern_ListAttendanceInternAll", kPKParameter);
        }
    
        public virtual ObjectResult<Intern_ListReportAttendanceForIntern_Result> Intern_ListReportAttendanceForIntern(string startDate, string endDate, string kPK)
        {
            var startDateParameter = startDate != null ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            var kPKParameter = kPK != null ?
                new ObjectParameter("KPK", kPK) :
                new ObjectParameter("KPK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Intern_ListReportAttendanceForIntern_Result>("Intern_ListReportAttendanceForIntern", startDateParameter, endDateParameter, kPKParameter);
        }
    
        public virtual ObjectResult<Intern_ListReportAttendanceIntern_Result> Intern_ListReportAttendanceIntern(string startDate, string endDate)
        {
            var startDateParameter = startDate != null ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Intern_ListReportAttendanceIntern_Result>("Intern_ListReportAttendanceIntern", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<Intern_MonitorIntern_Result> Intern_MonitorIntern(string startDate, string endDate, string mENTOR)
        {
            var startDateParameter = startDate != null ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            var mENTORParameter = mENTOR != null ?
                new ObjectParameter("MENTOR", mENTOR) :
                new ObjectParameter("MENTOR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Intern_MonitorIntern_Result>("Intern_MonitorIntern", startDateParameter, endDateParameter, mENTORParameter);
        }
    }
}
