//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRINTERNSHIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emergency_employee
    {
        public int Employee_code { get; set; }
        public string Emergency_name { get; set; }
        public string Emergency_address { get; set; }
        public string Emergency_relation { get; set; }
        public string Emergency_name_2 { get; set; }
        public string Emergency_contact { get; set; }
    }
}
