//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRINTERNSHIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDress
    {
        public string EMEMP { get; set; }
        public string Grade_code { get; set; }
        public string Grade_name { get; set; }
        public string Dress_name { get; set; }
        public string Exception { get; set; }
        public string Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string Expr3 { get; set; }
        public string Expr4 { get; set; }
        public string EMNAME { get; set; }
        public string EMGRAD { get; set; }
    }
}
