//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRINTERNSHIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historical_employee
    {
        public string employee_code { get; set; }
        public string employee_name { get; set; }
        public string plant { get; set; }
        public string department { get; set; }
        public string section { get; set; }
        public string job_title { get; set; }
        public string updated_at { get; set; }
        public int id_historical { get; set; }
        public string plant_after { get; set; }
        public string department_after { get; set; }
        public string section_after { get; set; }
        public string job_title_after { get; set; }
        public string status { get; set; }
    }
}
