//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRINTERNSHIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intern_Attendance
    {
        public string Cardholder_Name { get; set; }
        public string KPK { get; set; }
        public string Entry_Clock { get; set; }
        public string Entry_Card { get; set; }
        public string Entry_Date_Time { get; set; }
        public string Exit_Clock { get; set; }
        public string Exit_Card { get; set; }
        public string Exit_Date_Time { get; set; }
        public string Time_Worked { get; set; }
        public string Date { get; set; }
        public string StatusATN { get; set; }
        public string StatusABS { get; set; }
        public int Attendance_id { get; set; }
    }
}
