//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRINTERNSHIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intern_DetailContract
    {
        public int ID_Contract { get; set; }
        public string KPK { get; set; }
        public string DJoinDate { get; set; }
        public string DEndDate { get; set; }
        public string DExtend { get; set; }
    }
}
