//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRINTERNSHIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intern_AttendanceApproval
    {
        public string KPK { get; set; }
        public string ApprovalMentor { get; set; }
        public string ApprovalManager { get; set; }
        public string DateApprovedMentor { get; set; }
        public string DateApprovedManager { get; set; }
        public string DateSend { get; set; }
        public string StatusApproval { get; set; }
        public string StatusAttendance { get; set; }
        public string FilePatch { get; set; }
        public string Periode { get; set; }
        public int Approval_ID { get; set; }
    }
}
