//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRINTERNSHIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Public_Holidays
    {
        public int id { get; set; }
        public string Date_public_holidays { get; set; }
        public string Date_description { get; set; }
        public string Date_mandatory { get; set; }
        public string Type_mandatory { get; set; }
        public string Id_mandatory { get; set; }
    }
}
