//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRINTERNSHIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleList
    {
        public string username { get; set; }
        public string Expr1 { get; set; }
        public string password { get; set; }
        public string roles_id { get; set; }
        public string user_id { get; set; }
        public string Expr2 { get; set; }
        public string role_id { get; set; }
        public string role_name { get; set; }
    }
}
