//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRINTERNSHIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalHour
    {
        public string EMEMP { get; set; }
        public string periode_id { get; set; }
        public string Masa_kerja_date { get; set; }
        public string Masa_kerja_value { get; set; }
    }
}
