//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRINTERNSHIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwIntern_ReportPayment
    {
        public string KPK { get; set; }
        public string INTERNNAME { get; set; }
        public string BUDGET { get; set; }
        public string DEPT_NAME { get; set; }
        public string SECT_NAME { get; set; }
        public string SALARY { get; set; }
        public int Report_ID { get; set; }
        public Nullable<int> TAtn { get; set; }
        public Nullable<int> TAbs { get; set; }
        public Nullable<int> HalfWorkHour { get; set; }
        public Nullable<int> TDay { get; set; }
        public string DatePeriod { get; set; }
        public string Allowance { get; set; }
    }
}
