//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRINTERNSHIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwIntern_DashboardActLastWeek
    {
        public string test { get; set; }
        public string KPK { get; set; }
        public string Cardholder_Name { get; set; }
        public string MENTOR { get; set; }
        public string MANAGER { get; set; }
        public string ClockIn { get; set; }
        public string DateClockIn { get; set; }
        public string Entry_Date_Time { get; set; }
        public string ClockOut { get; set; }
        public string DateClockOut { get; set; }
        public string Entry_Out { get; set; }
        public Nullable<int> total_hour { get; set; }
        public int Attendance_id { get; set; }
        public Nullable<int> id { get; set; }
        public string Date_public_holidays { get; set; }
        public string Date_description { get; set; }
        public string Date_mandatory { get; set; }
        public string Type_mandatory { get; set; }
        public string Activity { get; set; }
        public Nullable<int> Activity_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string STATUS { get; set; }
    }
}
