//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRINTERNSHIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwIntern_MasterDataIntern
    {
        public string KPK { get; set; }
        public string INTERNNAME { get; set; }
        public string BUDGET { get; set; }
        public string DEPT { get; set; }
        public string SECTION { get; set; }
        public string DOB { get; set; }
        public string PHONE { get; set; }
        public string PERSONALMAIL { get; set; }
        public string OFFICEMAIL { get; set; }
        public string UNIVERSITY { get; set; }
        public string MAJOR { get; set; }
        public string PROJECT { get; set; }
        public string MENTOR { get; set; }
        public string MANAGER { get; set; }
        public string JOINDATE { get; set; }
        public string ENDDATE { get; set; }
        public string EXTEND { get; set; }
        public string SALARY { get; set; }
        public string NIM { get; set; }
        public string NIK { get; set; }
        public string ADDRESS { get; set; }
        public string GENDER { get; set; }
        public int IDINTERN { get; set; }
        public string NAMEMENTOR { get; set; }
        public string DEPT_NAME { get; set; }
        public string SECT_NAME { get; set; }
        public string EMAILMENTOR { get; set; }
        public Nullable<int> YOS { get; set; }
        public Nullable<int> EOC { get; set; }
        public string NAMEMANAGER { get; set; }
        public string EMAILMANAGER { get; set; }
        public string STATUS { get; set; }
    }
}
